packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - cpu-features
  - esbuild
  - fallow
  - msw
  - prisma
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - vue-demi
