packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
