packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  fallow: true
  msw: true
  prisma: true
  sharp: true
  vue-demi: true

minimumReleaseAgeExclude:
  - cnfast@0.0.8
  - "@oxlint-tsgolint/darwin-arm64@7.0.2001"
  - "@oxlint-tsgolint/darwin-x64@7.0.2001"
  - "@oxlint-tsgolint/linux-arm64@7.0.2001"
  - "@oxlint-tsgolint/linux-x64@7.0.2001"
  - "@oxlint-tsgolint/win32-arm64@7.0.2001"
  - "@oxlint-tsgolint/win32-x64@7.0.2001"
  - oxlint-tsgolint@7.0.2001
  - oxlint-config-awesomeness@3.3.0
  - "@next/env@16.3.0"
  - "@next/swc-darwin-arm64@16.3.0"
  - "@next/swc-darwin-x64@16.3.0"
  - "@next/swc-linux-arm64-gnu@16.3.0"
  - "@next/swc-linux-arm64-musl@16.3.0"
  - "@next/swc-linux-x64-gnu@16.3.0"
  - "@next/swc-linux-x64-musl@16.3.0"
  - "@next/swc-win32-arm64-msvc@16.3.0"
  - "@next/swc-win32-x64-msvc@16.3.0"
  - next@16.3.0
  - oxlint-plugin-react-doctor@0.9.6
  - "@react-email/ui@6.9.2"
  - react-email@6.9.2
